/*
 * Mini Kernel 2 for 386 PCs.
 * Version 0.1
 *
 * Author: Rafael Sabe
 * Email: rafaelmsabe@gmail.com
 */

#ifndef _MACROS_H
#define _MACROS_H

#define DISK_SECTOR_SIZE_BYTES 512

#define BOOTLOADER_DISKBLOCK_SIZE_SECTORS 1
#define BOOTLOADER_DISKBLOCK_SIZE_BYTES (BOOTLOADER_DISKBLOCK_SIZE_SECTORS*DISK_SECTOR_SIZE_BYTES)
#define BOOTLOADER_DISKBLOCK_SECTOR_INDEX 1
#define BOOTLOADER_MEMBLOCK_SIZE_BYTES BOOTLOADER_DISKBLOCK_SIZE_BYTES
#define BOOTLOADER_MEMBLOCK_SEG16 0x0
#define BOOTLOADER_MEMBLOCK_INDEX16 0x7c00
#define BOOTLOADER_MEMBLOCK_ADDR32 ((BOOTLOADER_MEMBLOCK_SEG16 << 4) | BOOTLOADER_MEMBLOCK_INDEX16)

#define GDT_DISKBLOCK_SIZE_SECTORS 1
#define GDT_DISKBLOCK_SIZE_BYTES (GDT_DISKBLOCK_SIZE_SECTORS*DISK_SECTOR_SIZE_BYTES)
#define GDT_DISKBLOCK_SECTOR_INDEX (BOOTLOADER_DISKBLOCK_SECTOR_INDEX + BOOTLOADER_DISKBLOCK_SIZE_SECTORS)
#define GDT_MEMBLOCK_SIZE_BYTES GDT_DISKBLOCK_SIZE_BYTES
#define GDT_MEMBLOCK_SEG16 0x0
#define GDT_MEMBLOCK_INDEX16 0x7e00
#define GDT_MEMBLOCK_ADDR32 ((GDT_MEMBLOCK_SEG16 << 4) | GDT_MEMBLOCK_INDEX16)

#define KERNEL_DISKBLOCK_SIZE_SECTORS 16
#define KERNEL_DISKBLOCK_SIZE_BYTES (KERNEL_DISKBLOCK_SIZE_SECTORS*DISK_SECTOR_SIZE_BYTES)
#define KERNEL_DISKBLOCK_SECTOR_INDEX (GDT_DISKBLOCK_SECTOR_INDEX + GDT_DISKBLOCK_SIZE_SECTORS)
#define KERNEL_MEMBLOCK_SIZE_BYTES 0x1ffff
#define KERNEL_MEMBLOCK_SEG16 0x1000
#define KERNEL_MEMBLOCK_INDEX16 0x0
#define KERNEL_MEMBLOCK_ADDR32 ((KERNEL_MEMBLOCK_SEG16 << 4) | KERNEL_MEMBLOCK_INDEX16)

#define DATA_MEMBLOCK_ADDR32 0x30000
#define DATA_MEMBLOCK_SIZE_BYTES 0x6ffff

#define VIDEO_MEMBLOCK_ADDR32 0xa0000
#define VIDEO_MEMBLOCK_SIZE_BYTES 0x1ffff

/* GENERAL PARAMS */

#define BOOTDEVID_SEG16 0x0
#define BOOTDEVID_INDEX16 0x7bfe
#define BOOTDEVID_ADDR32 ((BOOTDEVID_SEG16 << 4) | BOOTDEVID_INDEX16)

#define STACK_INIT_BP32 0xa0000

/* IDT PRE DEFINITIONS (Those may change once kernel is loaded up) */

/*#define IDT_MEMBLOCK_ADDR32 0x8000
#define IDT_MEMBLOCK_SIZE_BYTES 0x7fff*/

/* GDT BLOCK PARAMS */

#define GDTSEG_SIZE_BYTES 8

#define GDT_DESC_ADDR32 GDT_MEMBLOCK_ADDR32
#define GDT_DESC_SIZE_BYTES 8

#define GDT_ADDR32 (GDT_DESC_ADDR32 + GDT_DESC_SIZE_BYTES)

#define GDTSEG_COUNT 3
#define GDT_SIZE_BYTES (GDTSEG_COUNT*GDTSEG_SIZE_BYTES)

#define GDTSEG_KERNEL_INDEX 1
#define GDTSEG_KERNEL_OFFSET (GDTSEG_KERNEL_INDEX*GDTSEG_SIZE_BYTES)

#define GDTSEG_DATA_INDEX 2
#define GDTSEG_DATA_OFFSET (GDTSEG_DATA_INDEX*GDTSEG_SIZE_BYTES)

#endif /*_MACROS_H*/

